### ISSUE TITLE
Frequent S3 Slowdown Error

### ISSUE THREAD

**Issue by theyorubayesian** [huggingface/datatrove#302]
When processing CommonCrawl, I frequently get SlowDown Errors: `{'Error': {'Code': 'SlowDown', 'Message': 'Please reduce your request rate.'}`. Is this common? Are there any recommended strategies for alleviating this issue?

**Comment by hynky1999** [comment]
The issue here is on CommonCrawl side unfortunately. The s3 bucket is shared resource so there is high demand here. You can monitor the current use here https://status.commoncrawl.org/.

To mitigate the issue you can try:
1. Reducing number of concurrent downloands (reduce number of workers).
2. Use the random sleep feature for each worker so they don't all start fetching at the same time
3. Increase retries for aws fetching (it should be env variable)

**Comment by theyorubayesian** [comment]
Thanks for the response, @hynky1999. I'm sorry for raising an issue. I couldn't find a discussion section where I might ask. 

Also, I'm writing output while processing to Azure adlfs but nothing has been written so far. I can see that documents have passed through my filters successfully because I logged details but nothing has been written to adlfs. Is there a minimum size because pushes happen?
